### ISSUE TITLE
MDA requries updating for Denizen 1.1

### ISSUE THREAD

**Issue by SXRWahrheit** [BerndiVader/mmDenizenAddon#9]
Denizen 1.1.0 includes breaking changes that MythicDenizenAddon needs to be updated for. Scripts relying on MDA are broken in Denizen 1.1.0.

```
[09:05:05] [Server thread/ERROR]: Error occurred while enabling MythicDenizenAddon v0.511a-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: net/aufdemrand/denizencore/tags/TagManager
	at com.gmail.berndivader.mythicdenizenaddon.SupportManager.<init>(SupportManager.java:27) ~[?:?]
	at com.gmail.berndivader.mythicdenizenaddon.MythicDenizenPlugin.onEnable(MythicDenizenPlugin.java:37) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-e8ded36-acbc348]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-e8ded36-acbc348]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-e8ded36-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-e8ded36-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-e8ded36-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizencore.tags.TagManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-e8ded36-acbc348]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-e8ded36-acbc348]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	... 13 more
```
Among other issues, `net.aufdemrand` becomes `com.denizenscript`

**Comment by PikaMug** [comment]
Haven't looked into the intricacies of this, but Quests is currently using reflection to support both <1.1.0 and 1.1.0+ versions of Denizen. Perhaps it could be expanded upon for this addon?

https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/util/DenizenAPI.java
https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/util/DenizenAPI_1_1_0.java

**Comment by SXRWahrheit** [comment]
Denizen 1679 is the first Denizen 1.1.0 "release" and is now available, per:

https://discordapp.com/channels/315163488085475337/535851557196005388/607087257417154591
